### ISSUE TITLE
你的unitree_guide_go2代码上传的有问题，下载下来的还是宇树原来go1的代码，

### ISSUE THREAD

**Issue by rosbing** [Teddy-Liao/unitree_guide_go2#1]

**Comment by USTCzbb** [comment]
https://github.com/Teddy-Liao/unitree_guide_go2/commit/89b084263576a517a3968ad454424e731302a151
上面这个链接全是你的修改痕迹，看起来很费劲

**Comment by Teddy-Liao** [comment]
不能。
